vagrant_name = "k8s-singlenode-debian"
Vagrant.configure("2") do |config|
  config.vm.box = "debian/buster64"
  config.vm.hostname = vagrant_name
  config.vm.provider "virtualbox" do |vb|
    vb.name = vagrant_name
    vb.memory = 2048
    vb.cpus = 2
  end
  config.vm.network "public_network", bridge: "Internet"
  config.vm.provision "shell", inline: <<-SHELL
    sudo apt-get update
    sudo apt-get -y install \
      apt-transport-https \
      ca-certificates \
      curl \
      gnupg-agent \
      software-properties-common
      curl -fsSL https://download.docker.com/linux/debian/gpg | sudo apt-key add -
      sudo add-apt-repository \
        "deb [arch=amd64] https://download.docker.com/linux/debian \
        $(lsb_release -cs) \
        stable"
      sudo apt-get update
      sudo apt-get install -y docker-ce docker-ce-cli containerd.io
      sudo usermod -aG docker vagrant
      sudo systemctl start docker
      curl -s https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key add -
      echo "deb https://apt.kubernetes.io/ kubernetes-xenial main" | sudo tee /etc/apt/sources.list.d/kubernetes.list
      sudo apt-get update
      sudo apt-get install -y kubelet kubeadm kubectl
      sudo apt-mark hold kubelet kubeadm kubectl
      sudo /sbin/swapoff -a
  SHELL
end