Vagrant.configure("2") do |config|
  config.vm.define "node1" do |node1|
    node1.vm.box = "debian/buster64"
    node1.vm.hostname = "rke-node1"
    node1.vm.provider "virtualbox" do |vb|
      vb.name = "rke-node1"
      vb.memory = 2048
      vb.cpus = 2
    end
    node1.vm.network "public_network", bridge: "Intel(R) Wireless-AC 9560 160MHz"
    node1.vm.network :private_network, ip: "192.168.56.101"
    node1.vm.network :forwarded_port, guest: 22, host: 30221, id: "ssh"
    node1.vm.provision "shell", inline: <<-SHELL
      sudo apt-get update
      sudo apt-get -y install \
        apt-transport-https \
        ca-certificates \
        curl \
        gnupg-agent \
        software-properties-common
        curl https://releases.rancher.com/install-docker/19.03.sh | sh
        sudo usermod -aG docker vagrant
        sudo systemctl start docker
        sudo /sbin/swapoff -a
    SHELL
  end
end